# Generated by Django 4.2 on 2025-01-20 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('area', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('stories', models.IntegerField()),
                ('mainroad', models.BooleanField()),
                ('guestroom', models.BooleanField()),
                ('basement', models.BooleanField()),
                ('hotwaterheating', models.BooleanField()),
                ('airconditioning', models.BooleanField()),
                ('parking', models.IntegerField()),
                ('prefarea', models.BooleanField()),
                ('furnishingstatus', models.CharField(choices=[('unfurnished', 'Unfurnished'), ('semi-furnished', 'Semi-Furnished'), ('furnished', 'Furnished')], max_length=15)),
            ],
        ),
    ]
