# Generated by Django 4.2 on 2025-02-13 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_customuser_bmi_and_more'),
        ('health_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser'),
        ),
    ]
